<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

use Drupal\e2e_paragraphs_entity\Includes\EntityParagraph;


/*
 * Implements hook_entity_view()
 */
function e2e_paragraphs_entity_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode){
  
  if($entity->getEntityTypeId() == 'paragraph' && $entity->bundle() == 'entity'){
    $paragraph = new EntityParagraph($entity);
    $build['field_entity_reference'] = array($paragraph->getMarkup()); 
  }
}