<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/*
 * Implements hook_theme()
 */
function e2e_paragraphs_system_block_theme(){
  return array(
    'paragraph_system_block' => array(
      'variables' => array('systemblock' => NULL,),
      'template' => 'paragraph_system_block',
    ),
  );
}

/*
 * Implements hook_entity_view()
 */
function e2e_paragraphs_system_block_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode){
  
  if($entity->getEntityTypeId() == 'paragraph' && $entity->bundle() == 'system_block'){
    
    $systemblock = '';
    
    $block = \Drupal\block\Entity\Block::load($entity->field_block_id->value);
    
    if($block)
      $systemblock = \Drupal::entityManager()->getViewBuilder('block')->view($block);
    
    $build['#systemblock'] = $systemblock;
    $build['#theme'] = 'paragraph_system_block';
    
  }
}
