<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/*
 * Implements hook_entity_view()
 */
function e2e_paragraphs_gallery_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode){
  if($entity->getEntityTypeId() == 'paragraph' && $entity->bundle() == 'gallery'){
    $build['field_images']['#prefix'] = '<div class="gallery">';
    $build['field_images']['#suffix'] = '</div>';
    $build['#attached']['library'][] = 'e2e_paragraphs_gallery/baguetteBox';
    $build['#attached']['library'][] = 'e2e_paragraphs_gallery/gallery';
  }
}