field.widget.settings.ContentTypesWidget:
    type: mapping
    label: 'Content types widget settings'
    mapping:
        exclusive:
            type: text
            label: 'Exclude selected content types'