e2e_newsletter.newslettertheme.*:
    type: config_entity
    label: 'Newsletter theme'
    mapping:
        id:
            type: string
            label: 'ID'
        label:
            type: label
            label: 'Label'
        theme:
            type: string
            label: 'Theme'